development:
  adapter: postgresql
  host: localhost
  database: trellis
  user: michael
  password:

test:
  adapter: postgresql
  host: localhost
  database: trellis_test
  user: michael
  password:

production:
  adapter: postgresql
  host: localhost
  database: trellis
  user: michael
  password:
